FROM python:3.12-slim
# Install Node.js and wscat
RUN apt-get update && apt-get install -y nodejs npm && npm install -g wscat
# Install Dash and Dash Extensions
RUN pip install dash dash-extensions gunicorn
WORKDIR /app
COPY apps/dash_app.py .
CMD ["python", "-m", "gunicorn", "-b", "0.0.0.0:80", "dash_app:server"]